### ISSUE TITLE
Test Credentials Throws Error

### ISSUE THREAD

**Issue by AdamBrodzinski** [DispatchMe/meteor-accounts-sms#6]
Just a heads up (though this might be a known issue)... if you use the Twilio test credentials a fibers error is thrown. Prod credentials work great though!

```
Meteor.call('sendToRecipients', 'foo');


undefined:
  at Object.Future.wait (/Users/adam/.meteor/packages/meteor-tool/.1.1.3.14hk320++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
  at RestClient.<anonymous> (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/meteor.js:174:24)
  at [object Object].Twilio.sendSMS (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/dispatch_twilio.js:63:52)
  at [object Object].sendToRecipients (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/app/server/rpc_methods.es6.js.js:23:24)
  at maybeAuditArgumentChecks (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
  at /Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/ddp.js:2358:18
  at [object Object]._.extend.withValue (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/meteor.js:989:17)
  at [object Object]._.extend.apply (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/ddp.js:2357:45)
  at [object Object]._.extend.call (/Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/packages/ddp.js:2300:17)
  at repl:1:8
  at /Users/adam/projects/sms-spike/notifications/.meteor/local/build/programs/server/shell-server.js:243:23

```

**Comment by derekcaneja** [comment]
Unfortunately, Twilio does not allow the use of test credentials with the lookup api.
